services:
  web-app:
    build:
     context: .       # the path to the Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./service:/service

    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
